import { Book } from '@/types';

// Sample book covers using placeholder images
// These will be replaced with actual Contentstack assets later
const COVER_BASE = 'https://images.unsplash.com/photo-';

export const mockBooks: Book[] = [
  {
    id: '1',
    title: 'The Midnight Library',
    author: 'Matt Haig',
    description: 'Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived. To see how things would be if you had made other choices.',
    coverImage: `${COVER_BASE}1544947950-fa07a98d237f?w=400&h=600&fit=crop`,
    genres: ['Fiction', 'Fantasy', 'Philosophy'],
    publishedDate: '2020-08-13',
    pageCount: 304,
    rating: 4.5,
    pdfUrl: '/sample.pdf',
    featured: true,
    popular: true,
  },
  {
    id: '2',
    title: 'Atomic Habits',
    author: 'James Clear',
    description: 'No matter your goals, Atomic Habits offers a proven framework for improving every day. James Clear reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.',
    coverImage: `${COVER_BASE}1589829085413-56de8ae18c73?w=400&h=600&fit=crop`,
    genres: ['Self-Help', 'Psychology', 'Business'],
    publishedDate: '2018-10-16',
    pageCount: 320,
    rating: 4.8,
    pdfUrl: '/sample.pdf',
    featured: true,
    popular: true,
  },
  {
    id: '3',
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    description: 'Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the Earth itself will perish. Except that right now, he doesn\'t know that. He can\'t even remember his own name.',
    coverImage: `${COVER_BASE}1614544048536-0d28caf77f41?w=400&h=600&fit=crop`,
    genres: ['Science Fiction', 'Adventure', 'Thriller'],
    publishedDate: '2021-05-04',
    pageCount: 496,
    rating: 4.7,
    pdfUrl: '/sample.pdf',
    featured: true,
  },
  {
    id: '4',
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    description: 'Timeless lessons on wealth, greed, and happiness. Money—investing, personal finance, and business decisions—is typically taught as a math-based field, where data and formulas tell us exactly what to do.',
    coverImage: `${COVER_BASE}1553729459-efe14ef6055d?w=400&h=600&fit=crop`,
    genres: ['Finance', 'Psychology', 'Self-Help'],
    publishedDate: '2020-09-08',
    pageCount: 256,
    rating: 4.6,
    pdfUrl: '/sample.pdf',
    popular: true,
  },
  {
    id: '5',
    title: 'Dune',
    author: 'Frank Herbert',
    description: 'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the "spice" melange.',
    coverImage: `${COVER_BASE}1531988042231-d39a9cc12a9a?w=400&h=600&fit=crop`,
    genres: ['Science Fiction', 'Fantasy', 'Adventure'],
    publishedDate: '1965-08-01',
    pageCount: 688,
    rating: 4.4,
    pdfUrl: '/sample.pdf',
    popular: true,
  },
  {
    id: '6',
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    description: 'Paulo Coelho\'s masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different than he imagined.',
    coverImage: `${COVER_BASE}1495446815901-a7297e633e8d?w=400&h=600&fit=crop`,
    genres: ['Fiction', 'Philosophy', 'Adventure'],
    publishedDate: '1988-01-01',
    pageCount: 208,
    rating: 4.3,
    pdfUrl: '/sample.pdf',
    featured: true,
  },
  {
    id: '7',
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    description: 'From a renowned historian comes a groundbreaking narrative of humanity\'s creation and evolution that explores the ways in which biology and history have defined us.',
    coverImage: `${COVER_BASE}1516979187457-637abb4f9353?w=400&h=600&fit=crop`,
    genres: ['History', 'Science', 'Philosophy'],
    publishedDate: '2011-01-01',
    pageCount: 443,
    rating: 4.5,
    pdfUrl: '/sample.pdf',
    popular: true,
  },
  {
    id: '8',
    title: 'The Silent Patient',
    author: 'Alex Michaelides',
    description: 'Alicia Berenson\'s life is seemingly perfect. Until one evening, her husband Gabriel returns home late from work, and Alicia shoots him five times in the face. She never speaks another word.',
    coverImage: `${COVER_BASE}1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop`,
    genres: ['Thriller', 'Mystery', 'Psychology'],
    publishedDate: '2019-02-05',
    pageCount: 336,
    rating: 4.2,
    pdfUrl: '/sample.pdf',
  },
  {
    id: '9',
    title: 'Educated',
    author: 'Tara Westover',
    description: 'An unforgettable memoir about a young girl who, kept out of school, leaves her survivalist family and goes on to earn a PhD from Cambridge University.',
    coverImage: `${COVER_BASE}1481627834876-b7833e8f5570?w=400&h=600&fit=crop`,
    genres: ['Memoir', 'Biography', 'Education'],
    publishedDate: '2018-02-20',
    pageCount: 334,
    rating: 4.6,
    pdfUrl: '/sample.pdf',
  },
  {
    id: '10',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    description: 'The story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, of lavish parties on Long Island at a time when The New York Times noted "icharged with society divorcées".',
    coverImage: `${COVER_BASE}1512820790803-83ca734da794?w=400&h=600&fit=crop`,
    genres: ['Fiction', 'Classics', 'Romance'],
    publishedDate: '1925-04-10',
    pageCount: 180,
    rating: 4.4,
    pdfUrl: '/sample.pdf',
  },
  {
    id: '11',
    title: 'Think Again',
    author: 'Adam Grant',
    description: 'Intelligence is usually seen as the ability to think and learn, but in a rapidly changing world, there\'s another set of cognitive skills that might matter more: the ability to rethink and unlearn.',
    coverImage: `${COVER_BASE}1519682337058-a94d519337bc?w=400&h=600&fit=crop`,
    genres: ['Psychology', 'Self-Help', 'Business'],
    publishedDate: '2021-02-02',
    pageCount: 320,
    rating: 4.4,
    pdfUrl: '/sample.pdf',
  },
  {
    id: '12',
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    description: 'Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely traveling any farther than his pantry or cellar. But his contentment is disturbed when the wizard Gandalf arrives.',
    coverImage: `${COVER_BASE}1535666669445-e8476f1f9f3b?w=400&h=600&fit=crop`,
    genres: ['Fantasy', 'Adventure', 'Classics'],
    publishedDate: '1937-09-21',
    pageCount: 310,
    rating: 4.7,
    pdfUrl: '/sample.pdf',
    featured: true,
  },
];

export const allGenres = [
  'Fiction',
  'Fantasy',
  'Science Fiction',
  'Philosophy',
  'Self-Help',
  'Psychology',
  'Business',
  'Adventure',
  'Thriller',
  'Mystery',
  'Romance',
  'History',
  'Science',
  'Biography',
  'Memoir',
  'Classics',
  'Education',
  'Finance',
];
